### ISSUE TITLE
Transfer documentation to GitHub wikis

### ISSUE THREAD

**Issue by jmerlan** [OpenDBO/OpenRFA#7]
- [ ] Move documentation from Drupal basic pages to Github Wikis.

- [ ] Link all menu items on Drupal to Github Wiki pages

- [ ] Create some sort of redirect to ensure external links currently linking to OpenRFA.org are redirected appropriately.

**Comment by vdubya** [comment]
@jmerlan should the documentation be in the **Code** section instead of the **Wiki**? The repository represents the website, and if the pages were treated as code it could be forked to support creating variants. Forking does not bring over Wikis.

**Comment by jmerlan** [comment]
I feel like it should be a wiki unless the code is executed/viewed on another platform. Thoughts?

**Comment by vdubya** [comment]
GitHub supports the idea of using Repos for website content: https://pages.github.com/

**Comment by vdubya** [comment]
https://lab.github.com/courses/introduction-to-html

**Comment by vdubya** [comment]
In terms of your comment about "executed/viewed on another platform", I see what you're saying. I still would like to see if we can have GitHub be the backend and OpenRFA.org be the front end for the typical user. I feel like linking from openrfa.org to github.com would be confusing for most casual users.

Could we have a html file in github, host it from github, then iframe it into openrfa.org?

**Comment by jmerlan** [comment]
There are a few ways to accomplish what we are discussing here. I would still like to use some form of a CMS if possible though as it would save a lot of time from having to create templates from scratch. 

We can actually have a full static HTML page as a Drupal node with no theming: https://www.drupal.org/project/static_page

**Comment by vdubya** [comment]
How about using markdown in github? it would be limited but I don’t think the docs have anything markdown couldn’t already handle, no? It would complicate Drupal displaying it, but maybe a module like this could be employed?
https://www.drupal.org/project/markdown


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jmerlan** [comment]
If we store the content only (no wrappers or templates) as plain text using markdown here on GitHub, this could actually work. I like it. 

We would just need to figure out how to display the body from GitHub on our Drupal site. Shouldn't be hard, but might take a custom module.

**Comment by jmerlan** [comment]
Ok, this is brilliant. I went ahead and created a test HTML file and with the simple PHP snippet below was able to pull the raw HTML directly from the GitHub repo. I think this is going to work! I will test an HTML file using markdown tomorrow.

`<?php include("https://raw.githubusercontent.com/OpenDBO/OpenRFA/master/WebApp/Documentation/Process/LifeCycle.html"); ?>`

**Comment by vdubya** [comment]
Fantastic! I’ll look tomorrow.


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jmerlan** [comment]
The test for the markdown is successful! Check it out the live MD from this GitHub repo being displayed as content here: http://openrfa.org/documentation/life-cycle-parameter
I am going to close this issue and create a separate issue for each documentation page.

**Comment by vdubya** [comment]
Did you test the flow chart image? Also, looks like it is not pulling in the bulleted list correctly.

**Comment by vdubya** [comment]
Hmm, specifically:
"Moderators will review the parameter against the follow criteria: - Follows the standard naming convention - Is not a duplicate (or similar) parameter to an "Approved" parameter - Is assigned the proper DATA TYPE - Contains a DESCRIPTION. A moderator may modify the parameter to ensure compliance with these standards."

The lower bulleted list works.

Let's iron this out completely before we move to the rest of the pages.

**Comment by vdubya** [comment]
This is so cool (using github backend). So it appears the bulleted list is fixed now and I found a typo. Not sure why but the bulleted list did not work without a carriage return above it. Line 18 fixed it.

Check out https://github.com/OpenDBO/OpenRFA/commit/9c7dc7047a50ba9c06af6b816b35be163c61658c

**Comment by jmerlan** [comment]
I left the flowchart off as I was considering converting to SVG so that it is editable in the event of a fork. Thoughts?

**Comment by vdubya** [comment]
Good idea on the SVG however I'd recommend adding the image for now and treat the SVG as an enhancement.
